{{- if and .Values.ingress.enabled (eq (include "besu-stack.ingressType" .) "httpproxy") .Values.rpcNodes.enabled }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "besu-stack.fullname" . }}-rpc
  labels:
    {{- include "besu-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: rpc
  {{- with (include "besu-stack.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  virtualhost:
    fqdn: {{ .Values.ingress.hostname }}
    {{- if .Values.ingress.tls.enabled }}
    tls:
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- else }}
      secretName: {{ include "besu-stack.fullname" . }}-tls
      {{- end }}
    {{- end }}
  routes:
    - conditions:
        - prefix: /
      services:
        - name: {{ include "besu-stack.rpcNodes.serviceName" . }}
          port: {{ .Values.rpcNodes.rpc.http.port }}
      timeoutPolicy:
        response: {{ .Values.ingress.httpproxy.responseTimeout }}
        idle: {{ .Values.ingress.httpproxy.idleTimeout }}
{{- end }}
