{{- if and .Values.rpcNodes.enabled .Values.rpcNodes.keys.inline }}
{{- /*
WARNING: Inline keys should only be used for development.
For production, use existingSecrets or existingSecret with external secret management.
*/ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "besu-stack.fullname" . }}-rpc-keys
  labels:
    {{- include "besu-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: rpc
  annotations:
    {{- with (include "besu-stack.annotations" .) }}
    {{- . | nindent 4 }}
    {{- end }}
    helm.sh/resource-policy: keep
    besu-stack/warning: "DEVELOPMENT ONLY - Use external secrets for production"
type: Opaque
data:
  {{- range $i, $key := .Values.rpcNodes.keys.inline }}
  rpc-{{ $i }}: {{ $key.privateKey | b64enc | quote }}
  {{- end }}
{{- end }}
